apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: my-demo-app-production

images:
  - name: gruejay/k8s-demo-flask-app
    newTag: 1.4.0

patches:
  - target:
      version: v1
      kind: Service
      name: flask-app-service
    patch: |-
      - op: add
        path: /spec/type
        value: LoadBalancer
  - target:
      version: v1
      kind: Service
      name: flask-app-service
    patch: |-
      - op: add
        path: /spec/ingressClassName
        value: nginx


configMapGenerator:
- name: flask-app-config
  behavior: merge
  literals:
  - FLASK_ENV=production


